services:
  pact.matcher:
    class: PhpPact\Consumer\Matcher\Matcher

  behat.matcher:
    class: SmartGamma\Behat\PactExtension\Infrastructure\Interaction\BehatMatcher
    arguments:
      - '@pact.matcher'

  pact.interaction_builder.factory:
    class: SmartGamma\Behat\PactExtension\Infrastructure\Factory\InteractionBuilderFactory

  pact.compositor:
    class: SmartGamma\Behat\PactExtension\Infrastructure\Interaction\InteractionCompositor
    arguments:
      - '@behat.matcher'

  pact.infrastructure:
    class: SmartGamma\Behat\PactExtension\Infrastructure\Pact
    arguments:
      - '@pact.interaction_builder.factory'
      - '@pact.compositor'
      - '%pact.common.config%'
      - '%pact.providers.config%'

  pact.provider.state:
    class: SmartGamma\Behat\PactExtension\Infrastructure\ProviderState\ProviderState

  pact.provider.authenticator:
    class:  SmartGamma\Behat\PactExtension\Context\Authenticator

  pact.context.initializer:
    class: SmartGamma\Behat\PactExtension\Context\Initializer\PactInitializer
    arguments:
      - '@pact.infrastructure'
      - '@pact.provider.state'
      - '@pact.provider.authenticator'
    tags: [{ name: context.initializer }]
